[package]
name = "tlsgen"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
directories-next = "2.0.0"
rcgen = "0.13.1"
rustls = { version = "0.23.19", features = ["ring"] }

